### ISSUE TITLE
"Can Equip Heart Canisters" doesn't seem to work.

### ISSUE THREAD

**Issue by katubug** [Traverse-Joe/Baubley-Heart-Canisters#28]
I have my config option set to:

>    # Can Equip Heart Canisters
>     B:canEquipHeartCanisterWithoutAmulet=true

And I'm using:
baubley-heart-canisters-1.12.2-2.0.2
forge-1.12.2-14.23.5.2825-universal
Baubles-1.12-1.5.2

But heart canisters can't be placed in any Bauble slots, they need the amulet in order to be equipped.

**Comment by Radient-Sora** [comment]
Ohh I forgot to remove that config( the hearts go in the amulet only now I
will push a fix tonight sometime

**Comment by katubug** [comment]
Gotcha! Thanks so much!
