### ISSUE TITLE
heart recipes don't show in just enough resoursces

### ISSUE THREAD

**Issue by benbenlaw** [Traverse-Joe/Baubley-Heart-Canisters#36]
heart recipes don't show in just enough resoursces (this mod shows mob drops in jei)

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/104593721-fd867600-5667-11eb-8c39-850363eccf79.png)

**Comment by Traverse-Joe** [comment]
this is because JER uses loottables to determine this info and I use a drop event system to determine them. It's best to add a tooltip if you plan on changing them.
