### ISSUE TITLE
Wither bone recipe problem.

### ISSUE THREAD

**Issue by Tombstone101** [Traverse-Joe/Baubley-Heart-Canisters#37]
So minecraft already has a wither bone, and bhc adds a wither bone. Because they use different nbt tags you have to use the wither bone from bhc for crafting recipes of the heart cannisters. Even though drop rates for bhc wither bone are configurable, raising them reduces vanilla wither bone drops. Why have the mod add one instead of using vanilla wither bone in the recipe. Is this as intended or an oversight? Its strange having 2 different wither bones that have different uses.

**Comment by UpcraftLP** [comment]
But Minecraft *doesn't* have wither bones :laughing:

**Comment by Tombstone101** [comment]
I have clearly been playing too much modded minecraft. I apologize after realizing that. Needed my daughter to point this out to me (she's 11). Thank her =D my bad
