### ISSUE TITLE
[1.16] Blue hearts don't drop from Evokers

### ISSUE THREAD

**Issue by Weedoof** [Traverse-Joe/Baubley-Heart-Canisters#38]
As the title.

In 1.16.4-1.1.2, blue hearts don't drop from evokers. I'm not sure if this is intentional, given that evokers are that much easier to find than they were in 1.12, thanks to village raids existing. 
It's worth noting that if enough are killed, they will eventually drop red hearts.

I'll admit, I'm not sure which branch is the active / most recent one, but if it's v3.0-1.16.1 then I think it's due to this file not actually checking if the mob killed is an evoker. 
https://github.com/Traverse-Joe/Baubley-Heart-Canisters/blob/v.3.0-1.16.1/src/main/java/com/traverse/bhc/common/util/DropHandler.java

**Comment by Traverse-Joe** [comment]
Try deleting the drops.json and letting it regenerate

**Comment by Weedoof** [comment]
Ah, yeah. Works like a charm now. Didn't realize I had to do that after updating to 1.1.2. Thanks a bunch!
