### ISSUE TITLE
Changing config for heart drop chance to 0.0 still drops hearts

### ISSUE THREAD

**Issue by Goldenlion5648** [Traverse-Joe/Baubley-Heart-Canisters#39]
I changed the config to [this](https://gist.github.com/Goldenlion5648/2d5f468021154b73bd6abf2365e80362)

yet zombies for example still drop a red heart

**Comment by UpcraftLP** [comment]
`0` is still a 1% chance due to how the code is written.

for now, just set it to `-1` to disable.
