### ISSUE TITLE
Heart amulet problem

### ISSUE THREAD

**Issue by Gogo08190** [Traverse-Joe/Baubley-Heart-Canisters#40]
Hello, with le latest version (1.16.5-1.1.9) my heart canister has no texture and I can't remove that from my curios slot.. 
![image](https://user-images.githubusercontent.com/41335079/127124358-fff65536-ef34-4655-bf4e-8b598ea16d2c.png)

**Comment by Traverse-Joe** [comment]
This looks like an issue with curios being saved to the player data one method would be trying to die and see if it removes
