### ISSUE TITLE
Red Heart Canister not craftable 

### ISSUE THREAD

**Issue by Loonypanda** [Traverse-Joe/Baubley-Heart-Canisters#41]
Not sure if I downloaded the right version of "mantle," but when attempting to craft a "red heart canister," the recipe doesn't come up. I'm on version 1.16.

**Comment by sparrowprime** [comment]
why you close this,now 2023.7,this bug is still here,i can`t make a "red heart canister",there is no recipe for it?
![图片](https://github.com/Traverse-Joe/Baubley-Heart-Canisters/assets/87871590/de44bd6a-94e4-4107-aa53-a5a49a88fdfe)

**Comment by Traverse-Joe** [comment]
The red hearts aren’t craft-able they drop from  hostile mobs unless specified otherwise via bhc/drops.json.

**Comment by sparrowprime** [comment]
this picture is the thing can "red heart" make.
I have many heart,but i can`t make canister.

**Comment by Merithor** [comment]
I would like to know several things.
Are you playing a Modpack?
-If so, what modpack?
What version of 1.16 Baubley Heart Canisters are you using? (in mods folder, 1.16.3-1.21 For example, the whole file name string)

**Comment by sparrowprime** [comment]
I`m so sorry.
My launcher automatically downloaded the "latest" version - but 1.1.9
When I discovered this issue, I was so enraged that I forgot to check if the downloaded mod was the latest version.
I'm very sorry for wasting your time and raising a fixed issue.
Your generous attitude makes me feel ashamed. I'm sorry

**Comment by Traverse-Joe** [comment]
no it's okay as a dev i want to make sure all issues are addressed as such I just wanted to verify all the info was correct some mods  break other mods and if that was the case i needed to make sure it was communicated to the other mod dev so that we don't have conflicting issues. You are perfectly fine.
