### ISSUE TITLE
Curios slot texture issue

### ISSUE THREAD

**Issue by AHL67** [Traverse-Joe/Baubley-Heart-Canisters#44]
Hi. The Curios slot background texture is not found when Minecraft loads and has a Minecraft "missing texture":
![Before Reload](https://user-images.githubusercontent.com/55105638/133897194-567a8003-b78e-4852-bb1b-1e148c9250e5.png)

But, if you reload the resources (either before or after entering a world), the texture is displayed correctly:
![After Reload](https://user-images.githubusercontent.com/55105638/133897203-e22b433d-ac05-4b93-b75a-bbca68ebf3cd.png)

I believe the problem is in `com\traverse\bhc\common\BaubleyHeartCanisters.class` where you load the texture from `slots/empty_heartamulet` instead of `textures/slots/empty_heartamulet.png`.

**Comment by Traverse-Joe** [comment]
Alright I will take a look at getting a fix out tonight
