### ISSUE TITLE
Crash When Moving Amulet Slot While GUI is Open

### ISSUE THREAD

**Issue by Darkosto** [Traverse-Joe/Baubley-Heart-Canisters#48]
Hello!

I've recently been able to replicate a crash involving the Amulet while the GUI is open. 

1. Open the Amulet GUI
2. Move the Amulet to another inventory slot
3. Close the GUI
4. Crash

I'm able to get this crash every time and confirmed with another player that it happens to them consistently also.

Baubly Heart Canisters: 1.0.0
Forge: 39.1.0
Minecraft: 1.18.1

Crash log: https://pastebin.com/qbDPc3z0

Thank you!

**Comment by Traverse-Joe** [comment]
Alright thanks for the find I will whip out a fix sometime soon thanks again for the report

**Comment by abused** [comment]
Heyo, this should be fixed now. The item shouldn't have been able to open the GUI in the off-hand anyways so this should cover that. Build should be coming shortly
