### ISSUE TITLE
Soul Heart Canisters do not work

### ISSUE THREAD

**Issue by James103** [Traverse-Joe/Baubley-Heart-Canisters#53]
To reproduce:
1. Create a new instance with Forge 43.1.55 and Minecraft 1.19.2.
2. Install Curios API 5.1.1.0.
3. Install Baubley Heart Containers 1.1.5.
4. Create a new world with cheats enabled.
5. Give yourself a Soul Heart Amulet and some Soul Heart Canisters.
6. Add the Soul Heart Canisters to the Heart Amulet.
7. Equip the Heart Amulet.
8. The Soul Heart Containers do not provide any additional health.

**Comment by Traverse-Joe** [comment]
The soul heart canister doesn’t give extra health. It is a stackable totem of undying essentially. If ur health drops below 0 they will activate
