### ISSUE TITLE
When equipping heart canisters or the heart amulet, health automatically regenerates to max possible

### ISSUE THREAD

**Issue by Goldenlion5648** [Traverse-Joe/Baubley-Heart-Canisters#9]
I think this could be used in a bit of a cheaty way. For example if you have 3 hearts left, you can equip a heart amulet with 10 of each heart type to instantly go up 30-40 hearts. Maybe this could be a config option to either keep the current behavior or make each heart increase the max possible health but doesn't set the current health to the max possible. (similar to how the old tinkers heart canisters worked)

**Comment by UpcraftLP** [comment]
Huh, I thought that was fixed? 🤔 

What version of BHC are you on?

**Comment by Goldenlion5648** [comment]
version 1.2.1
